quarkus:
  application:
    name: regelverk-graphql
  
  # HTTP configuration
  http:
    port: 8080
    host: 0.0.0.0
    cors:
      ~: true
      origins: http://localhost:3000,http://localhost:8080
      methods: GET,POST,OPTIONS
      headers: "*"
  
  # Database configuration
  datasource:
    db-kind: postgresql
    username: regelverk
    password: regelverk
    jdbc:
      url: jdbc:postgresql://localhost:5432/regelverk_db
      max-size: 16
      min-size: 2
  
  # Dev services (auto-start database in dev mode)
  devservices:
    enabled: true
    db:
      image-name: postgres:15-alpine
  
  # Logging
  log:
    level: INFO
    category:
      "no.regelverk":
        level: DEBUG
      "org.jooq":
        level: DEBUG

# GraphQL configuration
graphql:
  endpoint: /graphql
  graphiql:
    enabled: true
    path: /graphiql