version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: regelverk-db
    environment:
      POSTGRES_DB: regelverk_db
      POSTGRES_USER: regelverk
      POSTGRES_PASSWORD: regelverk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U regelverk -d regelverk_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: